/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MusicUploadRouteImport } from './routes/music/upload'
import { Route as MusicEditorRouteImport } from './routes/music/editor'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicUploadRoute = MusicUploadRouteImport.update({
  id: '/music/upload',
  path: '/music/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicEditorRoute = MusicEditorRouteImport.update({
  id: '/music/editor',
  path: '/music/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/music/editor': typeof MusicEditorRoute
  '/music/upload': typeof MusicUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/music/editor': typeof MusicEditorRoute
  '/music/upload': typeof MusicUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/music/editor': typeof MusicEditorRoute
  '/music/upload': typeof MusicUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/music/editor' | '/music/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/music/editor' | '/music/upload'
  id: '__root__' | '/' | '/about' | '/music/editor' | '/music/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MusicEditorRoute: typeof MusicEditorRoute
  MusicUploadRoute: typeof MusicUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/editor': {
      id: '/music/editor'
      path: '/music/editor'
      fullPath: '/music/editor'
      preLoaderRoute: typeof MusicEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/upload': {
      id: '/music/upload'
      path: '/music/upload'
      fullPath: '/music/upload'
      preLoaderRoute: typeof MusicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/music/editor' {
  const createFileRoute: CreateFileRoute<
    '/music/editor',
    FileRoutesByPath['/music/editor']['parentRoute'],
    FileRoutesByPath['/music/editor']['id'],
    FileRoutesByPath['/music/editor']['path'],
    FileRoutesByPath['/music/editor']['fullPath']
  >
}
declare module './routes/music/upload' {
  const createFileRoute: CreateFileRoute<
    '/music/upload',
    FileRoutesByPath['/music/upload']['parentRoute'],
    FileRoutesByPath['/music/upload']['id'],
    FileRoutesByPath['/music/upload']['path'],
    FileRoutesByPath['/music/upload']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MusicEditorRoute: MusicEditorRoute,
  MusicUploadRoute: MusicUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
