/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedAboutRouteImport } from './routes/_protected/about'
import { Route as ProtectedMusicVisualizerRouteImport } from './routes/_protected/music/visualizer'
import { Route as ProtectedMusicUploadRouteImport } from './routes/_protected/music/upload'
import { Route as ProtectedMusicBrowseRouteImport } from './routes/_protected/music/browse'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAboutRoute = ProtectedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMusicVisualizerRoute =
  ProtectedMusicVisualizerRouteImport.update({
    id: '/music/visualizer',
    path: '/music/visualizer',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMusicUploadRoute = ProtectedMusicUploadRouteImport.update({
  id: '/music/upload',
  path: '/music/upload',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMusicBrowseRoute = ProtectedMusicBrowseRouteImport.update({
  id: '/music/browse',
  path: '/music/browse',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/about': typeof ProtectedAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/music/browse': typeof ProtectedMusicBrowseRoute
  '/music/upload': typeof ProtectedMusicUploadRoute
  '/music/visualizer': typeof ProtectedMusicVisualizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteWithChildren
  '/about': typeof ProtectedAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/music/browse': typeof ProtectedMusicBrowseRoute
  '/music/upload': typeof ProtectedMusicUploadRoute
  '/music/visualizer': typeof ProtectedMusicVisualizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/about': typeof ProtectedAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_protected/music/browse': typeof ProtectedMusicBrowseRoute
  '/_protected/music/upload': typeof ProtectedMusicUploadRoute
  '/_protected/music/visualizer': typeof ProtectedMusicVisualizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/music/browse'
    | '/music/upload'
    | '/music/visualizer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/music/browse'
    | '/music/upload'
    | '/music/visualizer'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/about'
    | '/auth/login'
    | '/auth/register'
    | '/_protected/music/browse'
    | '/_protected/music/upload'
    | '/_protected/music/visualizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/about': {
      id: '/_protected/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ProtectedAboutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/music/browse': {
      id: '/_protected/music/browse'
      path: '/music/browse'
      fullPath: '/music/browse'
      preLoaderRoute: typeof ProtectedMusicBrowseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/music/upload': {
      id: '/_protected/music/upload'
      path: '/music/upload'
      fullPath: '/music/upload'
      preLoaderRoute: typeof ProtectedMusicUploadRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/music/visualizer': {
      id: '/_protected/music/visualizer'
      path: '/music/visualizer'
      fullPath: '/music/visualizer'
      preLoaderRoute: typeof ProtectedMusicVisualizerRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/_protected' {
  const createFileRoute: CreateFileRoute<
    '/_protected',
    FileRoutesByPath['/_protected']['parentRoute'],
    FileRoutesByPath['/_protected']['id'],
    FileRoutesByPath['/_protected']['path'],
    FileRoutesByPath['/_protected']['fullPath']
  >
}
declare module './routes/_protected/about' {
  const createFileRoute: CreateFileRoute<
    '/_protected/about',
    FileRoutesByPath['/_protected/about']['parentRoute'],
    FileRoutesByPath['/_protected/about']['id'],
    FileRoutesByPath['/_protected/about']['path'],
    FileRoutesByPath['/_protected/about']['fullPath']
  >
}
declare module './routes/auth/login' {
  const createFileRoute: CreateFileRoute<
    '/auth/login',
    FileRoutesByPath['/auth/login']['parentRoute'],
    FileRoutesByPath['/auth/login']['id'],
    FileRoutesByPath['/auth/login']['path'],
    FileRoutesByPath['/auth/login']['fullPath']
  >
}
declare module './routes/auth/register' {
  const createFileRoute: CreateFileRoute<
    '/auth/register',
    FileRoutesByPath['/auth/register']['parentRoute'],
    FileRoutesByPath['/auth/register']['id'],
    FileRoutesByPath['/auth/register']['path'],
    FileRoutesByPath['/auth/register']['fullPath']
  >
}
declare module './routes/_protected/music/browse' {
  const createFileRoute: CreateFileRoute<
    '/_protected/music/browse',
    FileRoutesByPath['/_protected/music/browse']['parentRoute'],
    FileRoutesByPath['/_protected/music/browse']['id'],
    FileRoutesByPath['/_protected/music/browse']['path'],
    FileRoutesByPath['/_protected/music/browse']['fullPath']
  >
}
declare module './routes/_protected/music/upload' {
  const createFileRoute: CreateFileRoute<
    '/_protected/music/upload',
    FileRoutesByPath['/_protected/music/upload']['parentRoute'],
    FileRoutesByPath['/_protected/music/upload']['id'],
    FileRoutesByPath['/_protected/music/upload']['path'],
    FileRoutesByPath['/_protected/music/upload']['fullPath']
  >
}
declare module './routes/_protected/music/visualizer' {
  const createFileRoute: CreateFileRoute<
    '/_protected/music/visualizer',
    FileRoutesByPath['/_protected/music/visualizer']['parentRoute'],
    FileRoutesByPath['/_protected/music/visualizer']['id'],
    FileRoutesByPath['/_protected/music/visualizer']['path'],
    FileRoutesByPath['/_protected/music/visualizer']['fullPath']
  >
}

interface ProtectedRouteChildren {
  ProtectedAboutRoute: typeof ProtectedAboutRoute
  ProtectedMusicBrowseRoute: typeof ProtectedMusicBrowseRoute
  ProtectedMusicUploadRoute: typeof ProtectedMusicUploadRoute
  ProtectedMusicVisualizerRoute: typeof ProtectedMusicVisualizerRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAboutRoute: ProtectedAboutRoute,
  ProtectedMusicBrowseRoute: ProtectedMusicBrowseRoute,
  ProtectedMusicUploadRoute: ProtectedMusicUploadRoute,
  ProtectedMusicVisualizerRoute: ProtectedMusicVisualizerRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
